### ISSUE TITLE
Are there any requirements for the PCA_whitening_data?

### ISSUE THREAD

**Issue by xiaozhi2015** [yahoo/crow#8]
Should they have the same distribution with the under test data @yahoocla

**Comment by xiaozhi2015** [comment]
@pumpikano  Much thx!

**Comment by pumpikano** [comment]
Yes, ideally the data used to fit whitening will have the same distribution as the test data.

**Comment by xiaozhi2015** [comment]
Well,  can I generate a subset from my test data as the pca_whitening_data? @pumpikano

**Comment by pumpikano** [comment]
If you are benchmarking, the test data really should be separate from the data you use for whitening (otherwise you are testing on the training data). In practice, it is reasonable to use your index data to fit the whitening, although you could risk overfitting if your test-time query images are from a different distribution (e.g. mobile phone query images but professionally-shot index images).

**Comment by xiaozhi2015** [comment]
OK, much thx for your answer!
